### ISSUE TITLE
TicketMachine: Atributos devem ser privados

### ISSUE THREAD

**Issue by tormink** [tormink/Source-Code-Inspection#1]
Atributos devem ser privados, e o código não apresenta nenhuma razão para estes atributos serem protected.

```
    protected int valor;
    protected int saldo;
    protected int[] papelMoeda = {2, 5, 10, 20, 50, 100};
```

**Comment by YolHeh** [comment]
Linha 13, 14, 15

**Comment by tormink** [comment]
Atributos agora são privados e algumas variáveis podem ser constantes, dados os requisitos do projeto, por isso foram alteradas para constantes.

```
    private final int[] PAPELMOEDA = {2, 5, 10, 20, 50, 100};
    private final int VALOR;
    
    private int saldo;
```
